### PR TITLE
adding JRCVNC2018U template

### PR DESCRIPTION
**Pull request by istvantaisz**
Unisex VNC template from Bogovic et al 2018

### CODE REVIEW

**Comment by jefferis** [comment]
Hi @istvantaisz, thanks a lot for this. Would it be possible to add the docs for these objects as well using these as a template:

https://github.com/natverse/nat.flybrains/blob/36c622a15942c7a72e4a214668509c54ed0a4819/R/JRC2018.R#L79-L116

In fact I would probably suggest making a new `JRCVNC.R` source file for these docs.

**Comment by istvantaisz** [comment]
Hi @jefferis 
I made the separate JRCVNC.R and added the details to the unisex VNC in 08defbe

**Comment by jefferis** [comment]
>Hi @jefferis  ...

@istvantaisz Thanks! But can you run roxygen2 to generate the docs? There’s a shortcut in rstudio or you can do `devtools::check_man()` to build and make sure all is ok. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jefferis** [comment]
> ...

@istvantaisz ping?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by istvantaisz** [comment]
it seems good after f82ae18, there was a broken reference I didn't find for some time...

**Pull request merged**
