### PR TITLE
adding JRC2018F_VNC templatebrain

### PR DESCRIPTION
**Pull request by istvantaisz**

### CODE REVIEW

**Comment by jefferis** [comment]
Hi @istvantaisz, Thanks for this. Can you 

1. remove the DS_store (I suggest adding it to your global gitignore – google will tell you how)
2. I have restarted the travis build (which errored because of something to do with the new 4.0 version of R being incompatible with some cached versions of dependency packages on travis).
3. On reflection the short name would ideally not include an underscore since that is used to separate template brains in bridging registrations. So maybe simply `JRC2018FVNC` or `JRCVNC2018F`. I think given that the hemibrain is called `JRCFIB2018F` maybe the VNC should come first but I am not dogmatic.
4. @bogovicj do you have a view on what the short name for the VNC templates should be?

**Comment by bogovicj** [comment]
I also like `JRCVNC2018F` both for the sound of it and for consistency with the hemibrain short name as you said :)

**Comment by istvantaisz** [comment]
Hi @jefferis I've made the above changes.

The surface wasn't generated exactly as the others described in the documentation, I will update the .surf file based on that

**Comment by jefferis** [comment]
> ﻿Hi @jefferis I've made the above changes.

Great!
> The surface wasn't generated exactly as the others described in the documentation, I will update the .surf file based on that
> 
How was it different? I normally try to keep them fairly small 18-25k vertices for convenient plotting. I also downsample/smooth the original image and then smooth the surface. There should be some hx Amira script files which give the gist if you want to redo anything.

**Comment by istvantaisz** [comment]
I updated the surface following the method used for the brains and changed the documentation accordingly.

**Comment by jefferis** [comment]
Thanks a lot @istvantaisz. A good test is whether you can use `Rvcg::vcgVolume` 
```
> Rvcg::vcgVolume(as.mesh3d(JRCVNC2018F.surf))
[1] 3511794
```
The new mesh now passes that test, so looks good to me.

**Comment by jefferis** [comment]
There are a few internal blobs, which is interesting. 

image

**Comment by istvantaisz** [comment]
hm, true. I suspect they are coming form the large axon tracts that were very low intensity on the image.
Is there some quick fix in Amira that fills holes in a volume or a way to split up this single surface into the separate blobs and then threshold based on size?

**Comment by jefferis** [comment]
I think we can leave those blobs, they are presumably non-neuropil areas. There could be interest in removing them for some purposes (and perhaps closing some of the in pouches). But no need now. Thanks again for the PR.

**Pull request merged**
